#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
MANAGERS_DIR="managers"
DOTBOT_DIR="${MANAGERS_DIR}/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${MANAGERS_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${MANAGERS_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

read -p "Do you wish to install nvim plugins now? [y/n]: " yn
case $yn in
    [Yy]* ) nvim +PlugInstall +qall;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
esac
